### ISSUE TITLE
What is [version] in kick command

### ISSUE THREAD

**Issue by SharkyJunior** [wrrulos/MCPTool#10]
Hello, whenever i want to use kick option, it requires some sort of version, so i wonder, version of what does it want?
![image](https://user-images.githubusercontent.com/67413544/176534203-e99d9be9-7f72-4e96-b199-a6100bc0fa73.png)

**Comment by Eviolett-C** [comment]
got the same issue, i tried the version i got from using `server example.server.gg` and it still doesnt work or when using kickall it says no players connected
