### ISSUE TITLE
pip install mcptool now working 

### ISSUE THREAD

**Issue by SpigotRCE** [wrrulos/MCPTool#177]
I get this error when doing 
C:\Users\Milkthedev\Desktop\MCPTool>pip install mcptool
ERROR: Could not find a version that satisfies the requirement mcptool (from versions: none)
ERROR: No matching distribution found for mcptool

**Comment by PiotrekIsLucky** [comment]
its dead rn

**Comment by cyberisonXD** [comment]
yas
it saying same @SpigotRCE

**Comment by wrrulos** [comment]
The update has not been loaded yet. It will be available on May 31.
