### ISSUE TITLE
localhost ip

### ISSUE THREAD

**Issue by error657756** [wrrulos/mcptool#182]
everytime fake proxy gives me this ip
127.0.0.1:33330
ngrok is fixed everything is downloaded i posted issue on mcptool server + reyi_ server but no one solved my problem this is the 6th time

**Comment by WalnutMusic740** [comment]
As mentioned in the [command documentation](https://github.com/wrrulos/MCPTool/blob/main/docs/commands.md#fake-proxy), it is only going to create a local proxy by default. You have to expose the local port manually. If you are using Ngrok, run `ngrok tcp 33330` (in another terminal window). To convert the Ngrok address into numerical IP address, just run it through the ping command without port: `ping <address>` (in another terminal window).
