### ISSUE TITLE
Issue on wsl ubuntu

### ISSUE THREAD

**Issue by Midia12** [wrrulos/mcptool#186]
`root@midia:~# mcptool
[INFO] Installing node modules...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'minecraft-protocol@1.47.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mineflayer@4.20.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'protodef@1.15.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'prismarine-chunk@1.35.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@2.9.2',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

added 98 packages, and audited 99 packages in 21s

9 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Traceback (most recent call last):
  File "/usr/local/bin/mcptool", line 5, in <module>
    from mcptool.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/mcptool/__init__.py", line 55, in <module>
    from .modules.commands.seeker import Command as SeekerCommand
  File "/usr/local/lib/python3.10/dist-packages/mcptool/modules/commands/seeker.py", line 6, in <module>
    from ..utilities.seeker.utilities import SeekerUtilities
  File "/usr/local/lib/python3.10/dist-packages/mcptool/modules/utilities/seeker/utilities.py", line 30
    logger.error(f'Invalid endpoint for seeker: {get_config_value('endpoints.seeker')}')
                                                                   ^^^^^^^^^
SyntaxError: f-string: unmatched '('`

**Comment by wrrulos** [comment]
I'll fix it today! Thanks

**Comment by wrrulos** [comment]
Bug fixed!
