### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by Prceek** [wrrulos/MCPTool#22]
Hi i have a problem with bungee function when i create bungee server everything is working in the mcptool console
![image](https://user-images.githubusercontent.com/118296568/201979352-5e1a9545-e7d2-41d5-91f1-173a2c903135.png)
but when i want to join it says this 
![image](https://user-images.githubusercontent.com/118296568/201979451-2e0925cc-cdfa-4a66-b725-d6045d99b96a.png)
i tried everything to fix this, please help me.

**Comment by craciu25yt** [comment]
The server don't has Bungeecord enabled. Not a MCPTool issue

**Comment by craciu25yt** [comment]
You can try finding another port with bungeecord enabled at spigot.yml
