### ISSUE TITLE
API token leaked

### ISSUE THREAD

**Issue by Sch8ill** [wrrulos/MCPTool#29]
Are you sure that you want to show your shodan api token in public?🤨
It's visible in the [config file](https://github.com/wrrulos/MCPTool/blob/main/settings/settings.json#L4).

The best way to fix this would be to update the config file and to devaluate the api token.

**Comment by wrrulos** [comment]
There is no problem with that.

**Comment by Sch8ill** [comment]
well, do i need to explain to you what an API token is and why you shouldn't leak it?

**Comment by Aikidooo** [comment]
Lol you should definitely remove this, people can and will use the API under your name.

**Comment by wrrulos** [comment]
I will tell you in simple words. NOT MY API

**Comment by Sch8ill** [comment]
@wrrulos It's your trouble then, I wouldn't be that happy to get an angry letter from shodan.
