### ISSUE TITLE
what is [Version] ?

### ISSUE THREAD

**Issue by valeriancarrote** [wrrulos/MCPTool#31]
I dont know what is [Version]. I try with the version of the game but it dosent work 
help me ! 
![image](https://user-images.githubusercontent.com/115652371/227302479-1fed691a-d985-4993-a373-2662afa2a5af.png)

**Comment by bob448** [comment]
Me too.

**Comment by bob448** [comment]
I tried 1.19.3 and it works so maybe use 1.19.3 servers instead

**Comment by wrrulos** [comment]
Mineflayer doesn't currently support version 1.19.4, that's why it says it's invalid.
