### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.checks'; 'utils' is not a package

### ISSUE THREAD

**Issue by Naster17** [wrrulos/MCPTool#36]
Traceback (most recent call last):
  File "/home/nik/MCPTool/main.py", line 7, in <module>
    from utils.checks.CommandArguments import check_command_arguments
ModuleNotFoundError: No module named 'utils.checks'; 'utils' is not a package

**Comment by wrrulos** [comment]
It's not reading the utils folder, check if the directory is in the parent folder.
