### ISSUE TITLE
[ERROR] The entered API key is not valid! Check the configuration file.

### ISSUE THREAD

**Issue by 678745877698767985** [wrrulos/MCPTool#48]
How to fix?

![api issue](https://github.com/wrrulos/MCPTool/assets/133597932/1ac70730-a373-4918-9e65-588aadf587d9)

**Comment by Zen-kun04** [comment]
> How to fix?
> 
> ![api issue](https://user-images.githubusercontent.com/133597932/238202859-1ac70730-a373-4918-9e65-588aadf587d9.JPG)

you didn't add the Shodan API key in the config file

**Comment by swarnimbandekar** [comment]
> > How to fix?
> > ![api issue](https://user-images.githubusercontent.com/133597932/238202859-1ac70730-a373-4918-9e65-588aadf587d9.JPG)
> 
> you didn't add the Shodan API key in the config file

And How Do You Add it???

**Comment by ivangabriel21** [comment]
Have you already fixed the problem?

**Comment by wrrulos** [comment]
Fixed.
