### ISSUE TITLE
NodeJs Error

### ISSUE THREAD

**Issue by swarnimbandekar** [wrrulos/MCPTool#51]
Sir, Iam getting an nodejs module not found error, the log is given below please do check

[error.txt](https://github.com/wrrulos/MCPTool/files/11711789/error.txt)

![error](https://github.com/wrrulos/MCPTool/assets/68631900/50966430-1224-4f93-920b-197b37ad4332)

**Comment by Zen-kun04** [comment]
You need to install the module minecraft-colors

npm install minecraft-colors

**Comment by swarnimbandekar** [comment]
> You need to install the module minecraft-colors
> 
> npm install minecraft-colors

Figured it out, by the way thanks a lot XD
Let's Close this
