### ISSUE TITLE
Fakeproxy issue, cant find servers issue

### ISSUE THREAD

**Issue by MyLifeIsSakura** [wrrulos/MCPTool#61]
when i try to connect to the fakeproxy server it says it isnt a server (cannot connect to server) and when i try to do kick or kickall or something it says server is closed or unable to connect (ipinfo and dnslookup still works) also i have all the requirements and the things i needed to sownload in setup.py, when i use fake proxy before generating the proxy it says i dont have ngrok (which i fcking do) should i move ngrok to MCPTool folder? plz help and respond!

**Comment by MyLifeIsSakura** [comment]
im on windows btw

**Comment by ds775** [comment]
i aslo want to ask this
