### ISSUE TITLE
 Error whenstarting the run.bat

### ISSUE THREAD

**Issue by Nerd10000** [wrrulos/MCPTool#72]
I got this first: 

                                      ,
                                 .;xxxxxxx;.
                            .;xxxxxxxx%%xxxxxxx;.
                       .;xxxxxx%%++xx%%xxxxx%%xxxxxx;.
                  .;xxxx%%xxx%%xxx%%xxxxxxxxx%++x%%xxxxxx;.                ▶ MCPTool | Update ◀
                  |**'*-.xxxxxxxxxxxxxx++xxxxxxx%%%x.-*'**|
                  |*******`"-.;x%%@@%%++x%%xxx;.-"`*******|          • Checking for updates from MCPTool..
                  |::`;********`"-.xxxxxxx.-"`*********:::|
                  |::::"`:::`*******`"x"`*********,***`:::|          • A new version of the program was found.
                  |::::::::::::*******|*****`***"`::::::::|
                  |:::::cc:::::::"'-**|*`"**::::::::::cc::|          • Download the new version from:
                  |::cc:::::::::::::::|::::::::::::cc:::::|
                  |:::::::cc::::::cc::|::::::cc:::::::::::|          https://github.com/wrrulos/MCPTool
                  |::cc:::::::::::::::|::cc:::::cc::::::::|
                  :;::::::::::cc::::::|::::::::::::::::::;:
                     `":;:::::::::::::|::::cc:::::::;:"`
                          `":;::::cc::|::::::::;:`
                               `":;:::|:::;:"`
                                    `":"`

after it closes I followed the guide. By Nerd

**Comment by CoderStealer** [comment]
https://github.com/wrrulos/MCPTool/issues/71
here :)

**Comment by Nerd10000** [comment]
Works now Thanks
