### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by L30nard0100b** [wrrulos/MCPTool#81]
This repo got deleted i guess so anyone got the latest version of it? Can anyone send it?
Thanks

**Comment by danik228a** [comment]
Hi.
The developer in his Discord server explained that he only removed old versions and will do an update in the development branch during the week. Many people are left without the last version, we can only wait, don't worry so much.

**Comment by WalnutMusic740** [comment]
Yes, as @danik228a said. The developer has reset the *main* branch and will do updates to the *development* branch, so there is no way to download the latest working version (currently 4.1.2) from this repository. However, you can still download this version from a fork. For example this one, which has the latest version source code and the code has been unchanged: https://github.com/kenllyacosta/MCPTool

**Comment by L30nard0100b** [comment]
ok ty
