### ISSUE TITLE
ERROR (ESPAÑOL)

### ISSUE THREAD

**Issue by Sebas22323** [wrrulos/MCPTool#82]
hola master tengo un problema,  estaba instalando la tool pero cuando abro el archivo run me sale checkeando actualizaciones y me saca instantaneamente ayuda

**Comment by Sebas22323** [comment]
![Captura de pantalla 2024-03-10 135213](https://github.com/wrrulos/MCPTool/assets/162913591/63cd5f8d-fd7b-45bc-ac08-67a3b41a1fd2)

**Comment by Sebas22323** [comment]
y justo ahí se me cierra, me podrías ayudar porfa

**Comment by craciu25yt** [comment]
eso pq se borro en lo que chequea la version. Espera a que wrrulos lo actualice o borralo manualmente
